#! /bin/bash
handle() { echo "vamp-lifter/run: got signal"; exit; }
trap handle SIGINT

: "${RUN_VAMP_LIFTER:=true}"

if [[ -z RUN_VAMP_LIFTER ]] ; then
  exit
fi

exec 2>&1
exec /usr/local/vamp/lifter
