#! /bin/bash
handle() { echo "metricbeat/run: got signal"; exit; }
trap handle SIGINT

if [[ -z $VAMP_ELASTICSEARCH_URL ]] ; then
  sv stop metricbeat
  exit
fi

[[ -e /usr/local/metricbeat/metricbeat.yml ]] || exit 1

exec 2>&1
exec /usr/local/metricbeat/metricbeat -c /usr/local/metricbeat/metricbeat.yml
